# Generated by Django 3.0.6 on 2020-06-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=100)),
                ('runningtime', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('agecut', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.CharField(max_length=100)),
                ('counting', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100, null=True)),
                ('add', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('birth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchday', models.CharField(max_length=100)),
                ('watchtime', models.IntegerField()),
                ('theater', models.IntegerField()),
                ('booking', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater', models.IntegerField()),
                ('watchday', models.CharField(max_length=100)),
                ('watchtime', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.Info')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchday', models.CharField(max_length=100)),
                ('watchtime', models.IntegerField()),
                ('theater', models.IntegerField(default='')),
                ('bookingday', models.DateTimeField()),
                ('seat', models.CharField(max_length=100)),
                ('person', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.Member')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.Info')),
            ],
        ),
    ]
