# Generated by Django 3.0.6 on 2020-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'member_member',
            },
        ),
    ]
