# Generated by Django 3.0.6 on 2020-06-11 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='photos/no_image.png', upload_to='photos/%Y/%m/%d')),
                ('title', models.TextField(max_length=100)),
                ('genre', models.TextField(max_length=100)),
                ('runningtime', models.TextField(max_length=100)),
                ('openday', models.TextField(max_length=100)),
                ('director', models.TextField(max_length=100)),
                ('actor', models.TextField(max_length=100)),
                ('agecut', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('counting', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('replyday', models.DateTimeField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Member')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Info')),
            ],
        ),
    ]
